### PR TITLE
Feature: Add option to dispatch events instead of using global functions

### PR DESCRIPTION
**Pull request by shahata**

### CODE REVIEW

**Comment by christopherjbaker** [comment]
We had been planning to add something like this for a while, so thank you ! I like the general idea here, though I'm concerned about a couple of things:
* this fully changes the behaviour of _all_ function props
* the final WC is expected to _not_ have a matching attribute
* [erroneous getters/setters](https://github.com/bitovi/react-to-web-component/blob/main/packages/core/src/core.ts#L153) are added to the prototype.

I think a slightly better approach would be to introduce an `events` object on the options. The keys would be in the React prop format as they are now, and the values would be like the value of the `dispatchEvents` object you added. This would resolve all 3 above, and I think the only needed change would be to loop over the events object after the `propNames` loop that's there. It would still modify `this[propsSymbol][prop]` as it does now.

Does that make sense?

**Comment by shahata** [comment]
Sounds great, I will update the pr soon

**Comment by christopherjbaker** [comment]
After talking this over more with Brad, we'd like to stick with my first suggestion above. The second one limits the ability to customize individual event options, and we have some ideas for future expansions that would also need this.

If you are having any trouble or don't fully understand the suggestion, I'd be happy to help or finish the PR if you'd like.

**Comment by shahata** [comment]
@christopherjbaker I adjusted the implementation according to your first suggestion. I'm not sure this is 100% what you went, so plz let me know before I update the docs.

**Comment by shahata** [comment]
@christopherjbaker any chance you can take a look?

**Review by christopherjbaker — APPROVED** [review]
That's exactly what I was suggesting. Thank you!

**Comment by christopherjbaker** [comment]
This was released in `@r2wc/core@v1.2.0`. It is a peer dependency of `@r2wc/react-to-web-component`, so you can re-install it at the same version and you should get the latest core.

**Comment by shahata** [comment]
@christopherjbaker note that as I mentioned above I didn't adjust the docs to the new implementation yet, so currently the api.md contains incorrect information. I can submit an update to the markdown probably next week if you'd like.

**Pull request merged**
